/**
 * Generated by scripts/build-sajdah-verses.ts — do not edit by hand.
 * The 15 sajdah marks (۩) of the Madinah Mushaf, in Mushaf order.
 * textAr: verbatim Tanzil Uthmani (prisma/data/quran-uthmani.json). textEn: Sahih International.
 * isIn10Muataqidah: the 10 prostrations the four Sunni schools agree on; the other 5 carry a madhhab note.
 */
export type SajdahVerse = {
  surahId: number;
  ayahNumber: number;
  referenceAr: string;
  referenceEn: string;
  textAr: string;
  textEn: string;
  /** One of the 10 agreed prostrations (the "سجل السجود" tab). */
  isIn10Muataqidah: boolean;
  noteAr?: string;
  noteEn?: string;
  sortOrder: number;
};

export const SAJDAH_VERSES_CATALOG: SajdahVerse[] = [
  {
    "surahId": 7,
    "ayahNumber": 206,
    "referenceAr": "سورة الأعراف - آية 206",
    "referenceEn": "Surah Al-A'raf — Verse 206",
    "textAr": "إِنَّ ٱلَّذِينَ عِندَ رَبِّكَ لَا يَسْتَكْبِرُونَ عَنْ عِبَادَتِهِۦ وَيُسَبِّحُونَهُۥ وَلَهُۥ يَسْجُدُونَ ۩",
    "textEn": "Indeed, those who are near your Lord [i.e., the angels] are not prevented by arrogance from His worship, and they exalt Him, and to Him they prostrate.",
    "isIn10Muataqidah": true,
    "sortOrder": 1
  },
  {
    "surahId": 13,
    "ayahNumber": 15,
    "referenceAr": "سورة الرعد - آية 15",
    "referenceEn": "Surah Ar-Ra'd — Verse 15",
    "textAr": "وَلِلَّهِ يَسْجُدُ مَن فِى ٱلسَّمَٰوَٰتِ وَٱلْأَرْضِ طَوْعًۭا وَكَرْهًۭا وَظِلَٰلُهُم بِٱلْغُدُوِّ وَٱلْءَاصَالِ ۩",
    "textEn": "And to Allāh prostrates whoever is within the heavens and the earth, willingly or by compulsion, and their shadows [as well] in the mornings and the afternoons.",
    "isIn10Muataqidah": true,
    "sortOrder": 2
  },
  {
    "surahId": 16,
    "ayahNumber": 50,
    "referenceAr": "سورة النحل - آية 50",
    "referenceEn": "Surah An-Nahl — Verse 50",
    "textAr": "يَخَافُونَ رَبَّهُم مِّن فَوْقِهِمْ وَيَفْعَلُونَ مَا يُؤْمَرُونَ ۩",
    "textEn": "They fear their Lord above them, and they do what they are commanded.",
    "isIn10Muataqidah": true,
    "sortOrder": 3
  },
  {
    "surahId": 17,
    "ayahNumber": 109,
    "referenceAr": "سورة الإسراء - آية 109",
    "referenceEn": "Surah Al-Isra — Verse 109",
    "textAr": "وَيَخِرُّونَ لِلْأَذْقَانِ يَبْكُونَ وَيَزِيدُهُمْ خُشُوعًۭا ۩",
    "textEn": "And they fall upon their faces weeping, and it [i.e., the Qur’ān] increases them in humble submission.",
    "isIn10Muataqidah": true,
    "sortOrder": 4
  },
  {
    "surahId": 19,
    "ayahNumber": 58,
    "referenceAr": "سورة مريم - آية 58",
    "referenceEn": "Surah Maryam — Verse 58",
    "textAr": "أُو۟لَٰٓئِكَ ٱلَّذِينَ أَنْعَمَ ٱللَّهُ عَلَيْهِم مِّنَ ٱلنَّبِيِّۦنَ مِن ذُرِّيَّةِ ءَادَمَ وَمِمَّنْ حَمَلْنَا مَعَ نُوحٍۢ وَمِن ذُرِّيَّةِ إِبْرَٰهِيمَ وَإِسْرَٰٓءِيلَ وَمِمَّنْ هَدَيْنَا وَٱجْتَبَيْنَآ ۚ إِذَا تُتْلَىٰ عَلَيْهِمْ ءَايَٰتُ ٱلرَّحْمَٰنِ خَرُّوا۟ سُجَّدًۭا وَبُكِيًّۭا ۩",
    "textEn": "Those were the ones upon whom Allāh bestowed favor from among the prophets of the descendants of Adam and of those We carried [in the ship] with Noah, and of the descendants of Abraham and Israel [i.e., Jacob], and of those whom We guided and chose. When the verses of the Most Merciful were recited to them, they fell in prostration and weeping.",
    "isIn10Muataqidah": true,
    "sortOrder": 5
  },
  {
    "surahId": 22,
    "ayahNumber": 18,
    "referenceAr": "سورة الحج - آية 18",
    "referenceEn": "Surah Al-Hajj — Verse 18",
    "textAr": "أَلَمْ تَرَ أَنَّ ٱللَّهَ يَسْجُدُ لَهُۥ مَن فِى ٱلسَّمَٰوَٰتِ وَمَن فِى ٱلْأَرْضِ وَٱلشَّمْسُ وَٱلْقَمَرُ وَٱلنُّجُومُ وَٱلْجِبَالُ وَٱلشَّجَرُ وَٱلدَّوَآبُّ وَكَثِيرٌۭ مِّنَ ٱلنَّاسِ ۖ وَكَثِيرٌ حَقَّ عَلَيْهِ ٱلْعَذَابُ ۗ وَمَن يُهِنِ ٱللَّهُ فَمَا لَهُۥ مِن مُّكْرِمٍ ۚ إِنَّ ٱللَّهَ يَفْعَلُ مَا يَشَآءُ ۩",
    "textEn": "Do you not see [i.e., know] that to Allāh prostrates whoever is in the heavens and whoever is on the earth and the sun, the moon, the stars, the mountains, the trees, the moving creatures and many of the people? But upon many the punishment has been justified. And he whom Allāh humiliates - for him there is no bestower of honor. Indeed, Allāh does what He wills.",
    "isIn10Muataqidah": true,
    "sortOrder": 6
  },
  {
    "surahId": 22,
    "ayahNumber": 77,
    "referenceAr": "سورة الحج - آية 77",
    "referenceEn": "Surah Al-Hajj — Verse 77",
    "textAr": "يَٰٓأَيُّهَا ٱلَّذِينَ ءَامَنُوا۟ ٱرْكَعُوا۟ وَٱسْجُدُوا۟ وَٱعْبُدُوا۟ رَبَّكُمْ وَٱفْعَلُوا۟ ٱلْخَيْرَ لَعَلَّكُمْ تُفْلِحُونَ ۩",
    "textEn": "O you who have believed, bow and prostrate and worship your Lord and do good - that you may succeed.",
    "isIn10Muataqidah": false,
    "noteAr": "السجدة الثانية في سورة الحج: يسجد فيها الشافعية والحنابلة، ولا يراها الحنفية والمالكية سجدة تلاوة.",
    "noteEn": "The second prostration of Surah Al-Hajj: prostrated by the Shafi‘i and Hanbali schools; the Hanafi and Maliki schools do not count it as a prostration of recitation.",
    "sortOrder": 7
  },
  {
    "surahId": 25,
    "ayahNumber": 60,
    "referenceAr": "سورة الفرقان - آية 60",
    "referenceEn": "Surah Al-Furqan — Verse 60",
    "textAr": "وَإِذَا قِيلَ لَهُمُ ٱسْجُدُوا۟ لِلرَّحْمَٰنِ قَالُوا۟ وَمَا ٱلرَّحْمَٰنُ أَنَسْجُدُ لِمَا تَأْمُرُنَا وَزَادَهُمْ نُفُورًۭا ۩",
    "textEn": "And when it is said to them, \"Prostrate to the Most Merciful,\" they say, \"And what is the Most Merciful? Should we prostrate to that which you order us?\" And it increases them in aversion.",
    "isIn10Muataqidah": true,
    "sortOrder": 8
  },
  {
    "surahId": 27,
    "ayahNumber": 26,
    "referenceAr": "سورة النمل - آية 26",
    "referenceEn": "Surah An-Naml — Verse 26",
    "textAr": "ٱللَّهُ لَآ إِلَٰهَ إِلَّا هُوَ رَبُّ ٱلْعَرْشِ ٱلْعَظِيمِ ۩",
    "textEn": "Allāh - there is no deity except Him, Lord of the Great Throne.",
    "isIn10Muataqidah": true,
    "sortOrder": 9
  },
  {
    "surahId": 32,
    "ayahNumber": 15,
    "referenceAr": "سورة السجدة - آية 15",
    "referenceEn": "Surah As-Sajdah — Verse 15",
    "textAr": "إِنَّمَا يُؤْمِنُ بِـَٔايَٰتِنَا ٱلَّذِينَ إِذَا ذُكِّرُوا۟ بِهَا خَرُّوا۟ سُجَّدًۭا وَسَبَّحُوا۟ بِحَمْدِ رَبِّهِمْ وَهُمْ لَا يَسْتَكْبِرُونَ ۩",
    "textEn": "Only those believe in Our verses who, when they are reminded by them, fall down in prostration and exalt [Allāh] with praise of their Lord, and they are not arrogant.",
    "isIn10Muataqidah": true,
    "sortOrder": 10
  },
  {
    "surahId": 38,
    "ayahNumber": 24,
    "referenceAr": "سورة ص - آية 24",
    "referenceEn": "Surah Sad — Verse 24",
    "textAr": "قَالَ لَقَدْ ظَلَمَكَ بِسُؤَالِ نَعْجَتِكَ إِلَىٰ نِعَاجِهِۦ ۖ وَإِنَّ كَثِيرًۭا مِّنَ ٱلْخُلَطَآءِ لَيَبْغِى بَعْضُهُمْ عَلَىٰ بَعْضٍ إِلَّا ٱلَّذِينَ ءَامَنُوا۟ وَعَمِلُوا۟ ٱلصَّٰلِحَٰتِ وَقَلِيلٌۭ مَّا هُمْ ۗ وَظَنَّ دَاوُۥدُ أَنَّمَا فَتَنَّٰهُ فَٱسْتَغْفَرَ رَبَّهُۥ وَخَرَّ رَاكِعًۭا وَأَنَابَ ۩",
    "textEn": "[David] said, \"He has certainly wronged you in demanding your ewe [in addition] to his ewes. And indeed, many associates oppress one another, except for those who believe and do righteous deeds - and few are they.\" And David became certain that We had tried him, and he asked forgiveness of his Lord and fell down bowing [in prostration] and turned in repentance [to Allāh].",
    "isIn10Muataqidah": false,
    "noteAr": "سجد فيها النبي ﷺ (رواه البخاري — رقم 1069). هي سجدة تلاوة عند الحنفية والمالكية، وسجدة شكر عند الشافعية والحنابلة.",
    "noteEn": "The Prophet ﷺ prostrated at it (Sahih al-Bukhari 1069). A prostration of recitation for the Hanafi and Maliki schools, and of gratitude for the Shafi‘i and Hanbali schools.",
    "sortOrder": 11
  },
  {
    "surahId": 41,
    "ayahNumber": 38,
    "referenceAr": "سورة فصلت - آية 38",
    "referenceEn": "Surah Fussilat — Verse 38",
    "textAr": "فَإِنِ ٱسْتَكْبَرُوا۟ فَٱلَّذِينَ عِندَ رَبِّكَ يُسَبِّحُونَ لَهُۥ بِٱلَّيْلِ وَٱلنَّهَارِ وَهُمْ لَا يَسْـَٔمُونَ ۩",
    "textEn": "But if they are arrogant - then those who are near your Lord [i.e., the angels] exalt Him by night and by day, and they do not become weary.",
    "isIn10Muataqidah": true,
    "noteAr": "موضع السجود عند الجمهور بعد الآية 38، وعند المالكية بعد الآية 37.",
    "noteEn": "The majority prostrate after verse 38; the Maliki school after verse 37.",
    "sortOrder": 12
  },
  {
    "surahId": 53,
    "ayahNumber": 62,
    "referenceAr": "سورة النجم - آية 62",
    "referenceEn": "Surah An-Najm — Verse 62",
    "textAr": "فَٱسْجُدُوا۟ لِلَّهِ وَٱعْبُدُوا۟ ۩",
    "textEn": "So prostrate to Allāh and worship [Him].",
    "isIn10Muataqidah": false,
    "noteAr": "سجد فيها النبي ﷺ (رواه البخاري — رقم 1067). لا يراها المالكية في المشهور من مذهبهم سجدة تلاوة.",
    "noteEn": "The Prophet ﷺ prostrated at it (Sahih al-Bukhari 1067). The well-known Maliki position does not count it as a prostration of recitation.",
    "sortOrder": 13
  },
  {
    "surahId": 84,
    "ayahNumber": 21,
    "referenceAr": "سورة الانشقاق - آية 21",
    "referenceEn": "Surah Al-Inshiqaq — Verse 21",
    "textAr": "وَإِذَا قُرِئَ عَلَيْهِمُ ٱلْقُرْءَانُ لَا يَسْجُدُونَ ۩",
    "textEn": "And when the Qur’ān is recited to them, they do not prostrate [to Allāh]?",
    "isIn10Muataqidah": false,
    "noteAr": "سجد فيها النبي ﷺ (رواه مسلم — رقم 578). لا يراها المالكية في المشهور من مذهبهم سجدة تلاوة.",
    "noteEn": "The Prophet ﷺ prostrated at it (Sahih Muslim 578). The well-known Maliki position does not count it as a prostration of recitation.",
    "sortOrder": 14
  },
  {
    "surahId": 96,
    "ayahNumber": 19,
    "referenceAr": "سورة العلق - آية 19",
    "referenceEn": "Surah Al-'Alaq — Verse 19",
    "textAr": "كَلَّا لَا تُطِعْهُ وَٱسْجُدْ وَٱقْتَرِب ۩",
    "textEn": "No! Do not obey him. But prostrate and draw near [to Allāh].",
    "isIn10Muataqidah": false,
    "noteAr": "سجد فيها النبي ﷺ (رواه مسلم — رقم 578). لا يراها المالكية في المشهور من مذهبهم سجدة تلاوة.",
    "noteEn": "The Prophet ﷺ prostrated at it (Sahih Muslim 578). The well-known Maliki position does not count it as a prostration of recitation.",
    "sortOrder": 15
  }
];

export const SAJDAH_VERSE_COUNT_MUATAQIDAH = SAJDAH_VERSES_CATALOG.filter((v) => v.isIn10Muataqidah).length;
export const SAJDAH_VERSE_COUNT_FULL = SAJDAH_VERSES_CATALOG.length;
