/**
 * Builds src/shared/data/figures-of-the-day.ts from scripts/lib/figures-of-the-day-2026.ts, resolving every
 * evidence phrase to a verbatim excerpt + standard number in the local Sahih al-Bukhari / Sahih Muslim editions.
 *
 *   npx tsx scripts/build-figures-of-the-day.ts          # rebuild
 *   npx tsx scripts/build-figures-of-the-day.ts --check  # fail if the committed file is out of date
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { findSahihPhrase, type SahihCollection } from './lib/sahihayn-lookup';
import { FIGURE_DEFINITIONS, FIGURE_SOURCES, FIGURES_CATALOG_VERSION } from './lib/figures-of-the-day-2026';

const OUT = join(process.cwd(), 'src', 'shared', 'data', 'figures-of-the-day.ts');

const COLLECTION_AR: Record<SahihCollection, string> = { bukhari: 'صحيح البخاري', muslim: 'صحيح مسلم' };
const RAWAHU: Record<SahihCollection, string> = { bukhari: 'رواه البخاري', muslim: 'رواه مسلم' };

/** Display cleanup only: drops RLM marks, quote marks and dangling punctuation around the verbatim words. */
function cleanExcerpt(text: string): string {
  return text
    .replace(/[\u200f\u200e"]/g, '')
    .replace(/\s+/g, ' ')
    .replace(/^[\s،,.:ـ]+|[\s،,.:ـ]+$/g, '')
    .trim();
}

const ids = new Set<string>();
const figures = FIGURE_DEFINITIONS.map((def) => {
  if (ids.has(def.id)) throw new Error(`Duplicate figure id: ${def.id}`);
  ids.add(def.id);
  const resolved = def.evidence.map((spec) => {
    const matches = findSahihPhrase(spec.collection, spec.phrase);
    const match = spec.number ? matches.find((m) => m.number === spec.number) : matches[0];
    if (!match) {
      throw new Error(`${def.id}: phrase not found in ${spec.collection}${spec.number ? ` #${spec.number}` : ''}: «${spec.phrase}»`);
    }
    return { collection: spec.collection, number: match.number, excerpt: cleanExcerpt(match.excerptAr) };
  });
  const evidence: {
    collection: SahihCollection;
    collectionAr: string;
    number: number;
    textAr: string;
    sourceAr: string;
  }[] = [];
  for (const r of resolved) {
    const same = evidence.find((e) => e.collection === r.collection && e.number === r.number);
    if (same) {
      same.textAr = `${same.textAr} … ${r.excerpt}`;
      continue;
    }
    evidence.push({
      collection: r.collection,
      collectionAr: COLLECTION_AR[r.collection],
      number: r.number,
      textAr: r.excerpt,
      sourceAr: `${RAWAHU[r.collection]} — رقم ${r.number}`,
    });
  }
  const { evidence: _specs, ...rest } = def;
  return { ...rest, evidence };
});

const out = `/**
 * Generated by scripts/build-figures-of-the-day.ts — do not edit by hand.
 * Edit scripts/lib/figures-of-the-day-2026.ts, rebuild, and bump FIGURES_CATALOG_VERSION there.
 * Evidence excerpts are verbatim from Sahih al-Bukhari (Fath al-Bari numbering) and Sahih Muslim
 * (Fuad Abd al-Baqi numbering), fawazahmed0/hadith-api editions.
 */
export type FigureEvidence = {
  collection: 'bukhari' | 'muslim';
  collectionAr: string;
  number: number;
  textAr: string;
  sourceAr: string;
};

export type FigureOfTheDay = {
  id: string;
  nameAr: string;
  nameEn: string;
  honorificAr: string;
  titleAr: string;
  titleEn: string;
  summaryAr: string;
  storyAr: string[];
  lessonAr: string;
  evidence: FigureEvidence[];
};

export const FIGURES_CATALOG_VERSION = ${FIGURES_CATALOG_VERSION};

export const FIGURE_SOURCES: { titleAr: string; authorAr: string }[] = ${JSON.stringify(FIGURE_SOURCES, null, 2)};

export const FIGURES_OF_THE_DAY: FigureOfTheDay[] = ${JSON.stringify(figures, null, 2)};
`;

if (process.argv.includes('--check')) {
  const current = readFileSync(OUT, 'utf8').replace(/\r\n/g, '\n');
  if (current !== out) {
    console.error('src/shared/data/figures-of-the-day.ts is out of date — run scripts/build-figures-of-the-day.ts');
    process.exit(1);
  }
  console.log(`figures-of-the-day.ts is up to date (${figures.length} figures).`);
} else {
  writeFileSync(OUT, out, 'utf8');
  const evidenceCount = figures.reduce((s, f) => s + f.evidence.length, 0);
  console.log(`Wrote ${OUT}: ${figures.length} figures, ${evidenceCount} verified narrations.`);
  for (const f of figures) console.log(`  ${f.id.padEnd(28)} ${f.evidence.map((e) => e.sourceAr).join(' | ')}`);
}
